### ISSUE TITLE
Fix json view display

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/blockexplorer#218]
Currently, the extrinsic JSON view shows  the JSON not collapsed by default
![image](https://user-images.githubusercontent.com/5139220/230184230-7d759871-fa13-44cc-ad01-827f33aaadc4.png)

This looks bad is the JSON is too long, and for that reason needs to be fixed to show just a small peak of the JSON, and if the user wants to view more, they can interact with the component to do so.

**Comment by isSerge** [comment]
Good point, I think we can move the JSON to the bottom (under main details) because it's too narrow on the side
